name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt, llvm-tools
          targets: thumbv8m.main-none-eabihf

      - run: cargo fmt -- --check
      - run: cargo clippy --features nrf9160 --target thumbv8m.main-none-eabihf
      - run: cargo clippy --features nrf9160,dns-async,defmt --target thumbv8m.main-none-eabihf
      - run: cargo clippy --features nrf9151 --target thumbv8m.main-none-eabihf
